_wandb:
    value:
        cli_version: 0.22.2
        e:
            b2g07oj4iejpveq9xttajckrctz9ah5z:
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "509721178112"
                        used: "429813092352"
                email: lsumit008@gmail.com
                executable: C:\Users\Lenovo\Desktop\Nepali_GEC\nepali_gec\myenv\Scripts\python.exe
                git:
                    commit: e6c534b1f378df9e7c88cd91f6a246923197f5fa
                    remote: https://github.com/Sumitlasiwa/Nepali_GEC.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-c0367ef1-748f-567f-d4bf-dc9ee513eec3
                host: SUMIT
                memory:
                    total: "16309932032"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\Lenovo\Desktop\Nepali_GEC\nepali_gec\src\train.py
                python: CPython 3.13.1
                root: C:\Users\Lenovo\Desktop\Nepali_GEC\nepali_gec
                startedAt: "2025-11-17T17:39:00.377503Z"
                writerId: b2g07oj4iejpveq9xttajckrctz9ah5z
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
            "3":
                - 16
            "4": 3.13.1
            "5": 0.22.2
            "6": 4.56.2
            "8":
                - 3
            "12": 0.22.2
            "13": windows-amd64
batch_size:
    value: 16
dataset_name:
    value: sumitaryal/nepali_grammatical_error_correction
early_stopping_patience:
    value: 3
gradient_accumulation_steps:
    value: 2
gradient_checkpointing:
    value: true
learning_rate:
    value: 0.0003
logging_steps:
    value: 10
lora_alpha:
    value: 32
lora_dropout:
    value: 0.05
lora_r:
    value: 16
lora_target_modules:
    value:
        - q
        - k
        - v
        - o
        - wi
        - wo
max_length:
    value: 64
model_id:
    value: google/mt5-small
num_epochs:
    value: 5
num_samples:
    value: 15
output_dir:
    value: ../outputs
prefix:
    value: 'वाक्य सच्याउनुहोस्: '
save_total_limit:
    value: 2
seed:
    value: 42
test_size:
    value: 0.2
use_8bit:
    value: true
use_fp16:
    value: false
use_lora:
    value: true
wandb_project:
    value: nepali-grammar-correction
warmup_ratio:
    value: 0.05
weight_decay:
    value: 0.01
